### ISSUE TITLE
how to get the contact point from TOI?

### ISSUE THREAD

**Issue by benblo** [Genbox/VelcroPhysics#56]
Hi,
I'm using `TimeOfImpact.CalculateTimeOfImpact()` to perform a shape-cast, which gives me back the TOI from which I can compute the position of my casting shape at the TOI.
But I'm also interested in the contact point/normal itself, and noticed the [CalculateTimeOfImpact](https://github.com/tainicom/Aether.Physics2D/blob/7f223ed0071f25b1607fc351ba42bf0a016bbefd/Physics2D/Collision/TimeOfImpact.cs) inline doc says to `use Distance() to compute the contact point and normal at the time of impact`... however I'm not sure what `Distance()` this is referring to, and I didn't find a particularly easy way to do this.

Best I managed was to use `Distance.ComputeDistance()`, but that seems super inefficient and redundant as it's already done by `TimeOfImpact.CalculateTimeOfImpact()`. Also, I'm not sure I'm handling all the cases in the same way as `CalculateTimeOfImpact`.

Is there a better way to do this?
And is there a reason `CalculateTimeOfImpact` doesn't output more info out of the box?

Thanks!

**Comment by Genbox** [comment]
TOI sweeps the shape along a path to the point of collision. Distance.ComputeDistance() is used by TOI and faster than TOI if you only need the point of collision and normal.

**Comment by Genbox** [comment]
Right, now I understand.

The internals try to limit the size of input/output structs and caches such that more of it will fit in the CPU cache. On most systems it is much faster to just run a single iteration of the distance function rather than storing a lot of (mostly) unused values filling up the cache.

It does not store the original value of the distance function in the cache or output as it is not needed for the engine itself. However, you can try and store the original values from the distance function in TOIOutput if you want to omit that one distance call.

**Comment by benblo** [comment]
OK, that's what I thought, that it could just be added to `TOIOutput`, but I haven't studied the loop closely enough that I felt sure where exactly to do that.
Do you think adding more data to `TOIOutput` would have a negative impact on cache performances for the general case? I don't have a good grasp on how heavily `CalculateTimeOfImpact` is used by the engine itself... not even sure it matters for my game as I mostly use the engine for collision detection, not real physics (no non-kinematic bodies, forces etc).

**Comment by Genbox** [comment]
Honestly, it probably wouldn't. However, if we take that approach everywhere it would have a big impact.

This engine was built many years ago and both computers & compilers have changed a lot since. Nowadays I have to use Intel VTune Amplifier to get the real numbers as pipelining, prefetching, cache coherence etc. all have a huge impact on tight loops. For the most part, a simple profiler is enough though.
